name: VNMetrics Super Bot

on:
  schedule:
    - cron: '30 2 * * *' # 9:30 AM VN
  workflow_dispatch:

permissions:
  contents: write

jobs:
  auto-scrape:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # CÃ i Ä‘áº·t thÆ° viá»‡n Puppeteer (TrÃ¬nh duyá»‡t áº£o)
      - name: Install Dependencies
        run: npm install axios cheerio puppeteer --no-save

      # Cháº¡y script (ÄuÃ´i .cjs)
      - name: Run Scraper Script
        run: node scripts/scrape-etf.cjs

      - name: Auto Commit Data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ğŸ“Š Auto-update ETF Data"
          file_pattern: 'public/etf_data.json'
          skip_fetch: true
